version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build

test: off

deploy:
  release: opsi-manager-v$(appveyor_build_version)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "$APPVEYOR_REPO_COMMIT_MESSAGE"
  provider: GitHub
  auth_token:
    secure: "$GH_KEY"
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
